"""2nd

Revision ID: 102b1fb71489
Revises: dde005a49ae8
Create Date: 2023-02-23 14:33:36.208658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102b1fb71489'
down_revision = 'dde005a49ae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
