"""simplifications-2

Revision ID: 37ab576a1c6d
Revises: 4cb1fa1101de
Create Date: 2023-03-01 08:45:22.341013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ab576a1c6d'
down_revision = '4cb1fa1101de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speaker', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_speaker_email', table_name='speaker')
    op.drop_index('ix_speaker_name', table_name='speaker')
    op.create_index(op.f('ix_speaker_name'), 'speaker', ['name'], unique=False)
    op.drop_column('speaker', 'email')
    op.drop_column('speaker', 'companyImage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('companyImage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('speaker', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_speaker_name'), table_name='speaker')
    op.create_index('ix_speaker_name', 'speaker', ['name'], unique=False)
    op.create_index('ix_speaker_email', 'speaker', ['email'], unique=False)
    op.alter_column('speaker', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
