"""5nd

Revision ID: 4edefff35c69
Revises: fa1c7e298d57
Create Date: 2023-02-23 16:37:05.483732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edefff35c69'
down_revision = 'fa1c7e298d57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
