"""test

Revision ID: 717685cb3fff
Revises: 91754446823c
Create Date: 2023-02-24 16:11:11.992444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717685cb3fff'
down_revision = '91754446823c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
