"""6nd

Revision ID: 73b095bf4a5e
Revises: 4edefff35c69
Create Date: 2023-02-23 16:51:54.625345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b095bf4a5e'
down_revision = '4edefff35c69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
