"""3nd

Revision ID: 8bbe758325a1
Revises: 102b1fb71489
Create Date: 2023-02-23 14:59:35.307176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbe758325a1'
down_revision = '102b1fb71489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
