"""test

Revision ID: 8c2be57914c5
Revises: 8c9e47e141ae
Create Date: 2023-02-24 16:24:59.340995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2be57914c5'
down_revision = '8c9e47e141ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
