"""test

Revision ID: 8c9e47e141ae
Revises: 717685cb3fff
Create Date: 2023-02-24 16:24:37.471718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9e47e141ae'
down_revision = '717685cb3fff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
