"""initial

Revision ID: 91754446823c
Revises: 
Create Date: 2023-02-24 16:06:15.343382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91754446823c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('scheduleAndLocation', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('activityType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_index(op.f('ix_activity_name'), 'activity', ['name'], unique=True)
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('profileImage', sa.String(), nullable=True),
    sa.Column('companyImage', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contacts', sa.String(), nullable=True),
    sa.Column('researchInterests', sa.String(), nullable=True),
    sa.Column('typeOfSpeaker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_email'), 'speaker', ['email'], unique=True)
    op.create_index(op.f('ix_speaker_id'), 'speaker', ['id'], unique=False)
    op.create_index(op.f('ix_speaker_name'), 'speaker', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('typeOfUser', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('profileImage', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contacts', sa.String(), nullable=True),
    sa.Column('researchInterests', sa.String(), nullable=True),
    sa.Column('cv', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('enrolled_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    op.create_table('queue_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    op.create_table('speaker_activity_table',
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('activity_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('speaker_id', 'activity_')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_activity_table')
    op.drop_table('queue_table')
    op.drop_table('enrolled_table')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_speaker_name'), table_name='speaker')
    op.drop_index(op.f('ix_speaker_id'), table_name='speaker')
    op.drop_index(op.f('ix_speaker_email'), table_name='speaker')
    op.drop_table('speaker')
    op.drop_index(op.f('ix_activity_name'), table_name='activity')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
