"""initial

Revision ID: a101b663ad8d
Revises: 
Create Date: 2023-02-23 00:14:23.184093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a101b663ad8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('scheduleAndLocation', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('activityType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=True)
    op.create_table('speakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('profileImage', sa.String(), nullable=True),
    sa.Column('companyImage', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contacts', sa.String(), nullable=True),
    sa.Column('researchInterests', sa.String(), nullable=True),
    sa.Column('typeOfSpeaker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_email'), 'speakers', ['email'], unique=True)
    op.create_index(op.f('ix_speakers_id'), 'speakers', ['id'], unique=False)
    op.create_index(op.f('ix_speakers_name'), 'speakers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('roles', sa.String(), nullable=True),
    sa.Column('profileImage', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contacts', sa.String(), nullable=True),
    sa.Column('researchInterests', sa.String(), nullable=True),
    sa.Column('cv', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('enrolled_table',
    sa.Column('users', sa.UUID(), nullable=False),
    sa.Column('activities', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activities'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users', 'activities')
    )
    op.create_table('queue_table',
    sa.Column('users', sa.UUID(), nullable=True),
    sa.Column('activities', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['activities'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_table')
    op.drop_table('enrolled_table')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_speakers_name'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_id'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_email'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
