"""test

Revision ID: c5776e6507b9
Revises: 1f2a8f19ff8f
Create Date: 2023-02-24 18:10:51.309394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5776e6507b9'
down_revision = '1f2a8f19ff8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
