"""simplifications-3

Revision ID: e7d58a9dcfce
Revises: 37ab576a1c6d
Create Date: 2023-03-01 10:48:30.432366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d58a9dcfce'
down_revision = '37ab576a1c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
