"""upload files

Revision ID: e9dbd7773bd8
Revises: e7d58a9dcfce
Create Date: 2023-03-01 12:17:34.524449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dbd7773bd8'
down_revision = 'e7d58a9dcfce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'profileImage')
    op.drop_column('user', 'profileImage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profileImage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('speaker', sa.Column('profileImage', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
