"""4nd

Revision ID: fa1c7e298d57
Revises: 8bbe758325a1
Create Date: 2023-02-23 15:16:09.121803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa1c7e298d57'
down_revision = '8bbe758325a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_activity_table')
    op.drop_table('enrolled_table')
    op.drop_table('queue_table')
    op.add_column('activities', sa.Column('speakers', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('activities', sa.Column('enrolledUser', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('activities', sa.Column('usersInQueue', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('speakers', sa.Column('activities', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('users', sa.Column('enrolledActivities', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enrolledActivities')
    op.drop_column('speakers', 'activities')
    op.drop_column('activities', 'usersInQueue')
    op.drop_column('activities', 'enrolledUser')
    op.drop_column('activities', 'speakers')
    op.create_table('queue_table',
    sa.Column('users', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('activities', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activities'], ['activities.id'], name='queue_table_activities_fkey'),
    sa.ForeignKeyConstraint(['users'], ['users.id'], name='queue_table_users_fkey')
    )
    op.create_table('enrolled_table',
    sa.Column('users', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activities', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activities'], ['activities.id'], name='enrolled_table_activities_fkey'),
    sa.ForeignKeyConstraint(['users'], ['users.id'], name='enrolled_table_users_fkey'),
    sa.PrimaryKeyConstraint('users', 'activities', name='enrolled_table_pkey')
    )
    op.create_table('speaker_activity_table',
    sa.Column('speaker', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity'], ['activities.id'], name='speaker_activity_table_activity_fkey'),
    sa.ForeignKeyConstraint(['speaker'], ['speakers.id'], name='speaker_activity_table_speaker_fkey'),
    sa.PrimaryKeyConstraint('speaker', 'activity', name='speaker_activity_table_pkey')
    )
    # ### end Alembic commands ###
